const $=id=>document.getElementById(id);let token=localStorage.getItem("el_token")||"",peerId=localStorage.getItem("el_peer")||crypto.randomUUID(),pending=JSON.parse(localStorage.getItem("el_pending")||"[]"),socket=null;localStorage.setItem("el_peer",peerId);
function net(){const o=navigator.onLine;$("net").textContent=o?"● Online":"● Offline";$("net").className="pill "+(o?"":"offline")}addEventListener("online",()=>{net();syncPending()});addEventListener("offline",net);net();
$("login").onclick=()=>auth("/api/auth/login");$("register").onclick=()=>auth("/api/auth/register");
async function auth(url){try{const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("email").value,password:$("password").value})}),j=await r.json();if(!r.ok)throw Error(j.error);token=j.token;localStorage.setItem("el_token",token);show()}catch(e){$("authMsg").textContent=e.message}}
function show(){$("auth").hidden=true;$("app").hidden=false;loadReports();signal()}
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.hidden=true);$(b.dataset.tab).hidden=false;if(b.dataset.tab==="dashboard")loadReports()});
$("incidentForm").onsubmit=async e=>{e.preventDefault();const item={id:crypto.randomUUID(),incidentType:$("incidentType").value,location:$("location").value,emergencyNumber:$("emergencyNumber").value,description:$("description").value,createdAt:new Date().toISOString()};if(!navigator.onLine){pending.push(item);save();$("sendMsg").textContent="Saved locally; waiting for synchronization.";e.target.reset();return}try{const r=await fetch("/api/incidents",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify(item)});if(!r.ok)throw Error();$("sendMsg").textContent="Emergency received by the cloud server.";e.target.reset();loadReports()}catch{pending.push(item);save();$("sendMsg").textContent="Connection failed; saved locally."}};
$("sync").onclick=syncPending;async function syncPending(){if(!navigator.onLine||!token||!pending.length)return;try{const r=await fetch("/api/incidents/sync",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({incidents:pending})});if(r.ok){pending=[];save();loadReports()}}catch{}}
function save(){localStorage.setItem("el_pending",JSON.stringify(pending))}
async function loadReports(){if(!token)return;try{const r=await fetch("/api/incidents",{headers:{Authorization:"Bearer "+token}});if(!r.ok)return;const rows=await r.json();$("reports").innerHTML=rows.map(x=>`<article class="report"><b>${safe(x.incident_type)}</b> <span class="status">${safe(x.status)}</span><p><b>Location:</b> ${safe(x.location)}<br><b>Emergency:</b> ${safe(x.emergency_number)}<br>${safe(x.description)}</p><small>${new Date(x.created_at).toLocaleString()} • ${safe(x.received_via)}</small></article>`).join("")||"<p>No cloud reports.</p>";if(pending.length)$("reports").insertAdjacentHTML("afterbegin",pending.map(x=>`<article class="report"><b>${safe(x.incidentType)}</b> <span class="status">pending offline</span><p>${safe(x.location)} — ${safe(x.description)}</p></article>`).join(""))}catch{}}
function safe(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function signal(){if(socket&&socket.readyState<=1)return;const p=location.protocol==="https:"?"wss":"ws";socket=new WebSocket(`${p}://${location.host}/signal`);socket.onopen=()=>socket.send(JSON.stringify({type:"hello",peerId}));socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="peers"){$("peerCount").textContent=m.peers.length;$("peerList").innerHTML=m.peers.map(x=>`<p>${safe(x)}</p>`).join("")||"<p>No peers currently connected.</p>"}};socket.onclose=()=>setTimeout(signal,3000)}
$("connectPeers").onclick=signal;if(token)show();if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});